language: cpp

before_install:
 - sudo apt-get update
 - sudo apt-get install cmake libboost-all-dev openmpi-bin libopenmpi-dev

script:
        - cmake . && make -j2 && sudo make install 

compiler:
  - gcc
